ALTER TABLE books ADD COLUMN regalo  BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE books ADD COLUMN trueque BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE books ADD COLUMN venta   BOOLEAN NOT NULL DEFAULT FALSE;
