export const TERMS_TITLE = 'Términos y Condiciones de Uso: Truequedelibros'

export const TERMS_PARAGRAPHS = [
  { heading: '1. Naturaleza de la Plataforma', body: 'Truequedelibros es una plataforma digital que facilita el contacto entre usuarios para el intercambio, compra y venta de libros entre pares. La Plataforma actúa exclusivamente como intermediario tecnológico. No somos propietarios de los libros publicados, no participamos en las transacciones físicas ni supervisamos la calidad, estado o existencia real de los ejemplares.' },
  { heading: '2. Funcionamiento de los "Puntos Seguros"', body: 'Los "Puntos Seguros" son locales comerciales externos que, de manera voluntaria, ofrecen sus instalaciones como puntos físicos de encuentro para facilitar la logística de entrega y recepción entre usuarios.' },
  { heading: '3. Exención de Responsabilidad sobre la Custodia', body: 'Al utilizar un "Punto Seguro", los usuarios reconocen y aceptan las siguientes condiciones:' },
  { body: 'Inexistencia de Contrato de Depósito: Los usuarios reconocen que el establecimiento ("EL ESTABLECIMIENTO") actúa únicamente como un punto físico de encuentro para facilitar el intercambio entre pares y no como un depositario. La entrega de ejemplares en EL ESTABLECIMIENTO no constituye un contrato de depósito, custodia ni resguardo por parte del local ni de la plataforma.' },
  { body: 'Asunción de Riesgo: El usuario que decida dejar un libro en el establecimiento lo hace bajo su exclusivo criterio, riesgo y responsabilidad.' },
  { body: 'Liberación de Responsabilidad: El usuario libera expresamente a EL ESTABLECIMIENTO y a LA PLATAFORMA de cualquier reclamo, demanda o indemnización derivada de la pérdida, deterioro, sustracción, daños físicos o la imposibilidad de retiro del ejemplar por parte del usuario receptor o emisor.' },
  { body: 'Renuncia de Acciones Legales: El usuario renuncia expresamente a realizar cualquier tipo de reclamo administrativo, extrajudicial o judicial contra el local o contra la plataforma por daños, faltantes o inconvenientes relacionados con los ejemplares intercambiados a través de estos puntos.' },
  { heading: '4. Responsabilidad entre Usuarios', body: 'Cualquier conflicto relacionado con el estado del libro, el pago (en caso de compraventa) o el cumplimiento del acuerdo de trueque debe ser resuelto exclusivamente entre las partes involucradas. La Plataforma no interviene en disputas de carácter privado entre usuarios.' },
  { heading: '5. Libros de Punto Seguro', body: 'Algunos libros publicados en la Plataforma pertenecen a un "Punto Seguro" y se identifican visualmente en el feed con un efecto distintivo. Estos libros no están disponibles para la venta y deben ser devueltos al mismo Punto Seguro una vez finalizada su lectura.' },
  { body: 'Mecanismo de retiro: para llevarse un libro de un Punto Seguro, el usuario debe dejar en el local uno de sus propios libros en buen estado. Una vez finalizada la lectura, el usuario puede optar por llevarse otro libro distinto del mismo Punto Seguro o retirar el libro que dejó al principio.' },
  { body: 'Plazo: el usuario dispone de 1 (un) mes desde el retiro para devolver el libro. Los usuarios con plan Premium cuentan con un plazo extendido de hasta 2 (dos) meses.' },
  { body: 'Es responsabilidad exclusiva del usuario informar por correo electrónico a contacto@truequedelibros.com qué libro retiró de un Punto Seguro, para que el equipo pueda actualizar la disponibilidad del libro y registrar el ejemplar dejado en su reemplazo. La Plataforma no realiza un seguimiento automático de los préstamos ni de sus vencimientos.' },
]
